### ISSUE TITLE
str error

### ISSUE THREAD

**Issue by Midnoclose** [archshift/ctr-elf#2]
I get
```
textBase: 00100000
textSize: 001a3000
roSize:   00031000
rwSize:   0002a000
bssSize:  01a6b000
Traceback (most recent call last):
  File "exefs2elf.py", line 46, in <module>
    writefile('workdir/e2elf.ld', ldscript)
  File "exefs2elf.py", line 16, in writefile
    f.write(str(s))
TypeError: a bytes-like object is required, not 'str'
```
When I attempt to use this.

**Comment by archshift** [comment]
If you replace that line with `f.write(bytes(s))`, do you get the output you expect?

**Comment by Midnoclose** [comment]
I realized the issue was that I was on Python 3.5

**Comment by Midnoclose** [comment]
But now My issue is this:
```
textBase: 00100000
textSize: 001a3000
roSize:   00031000
rwSize:   0002a000
bssSize:  01a6b000
'arm-none-eabi-objcopy' is not recognized as an internal or external command,
operable program or batch file.
'arm-none-eabi-objcopy' is not recognized as an internal or external command,
operable program or batch file.
'arm-none-eabi-objcopy' is not recognized as an internal or external command,
operable program or batch file.
'arm-none-eabi-ld' is not recognized as an internal or external command,
operable program or batch file.
```
And I beleive it is because I am on windows.
